config/routes.rb
Rails.application.routes.draw do
  
  
  # get 'credit_cards/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions'   
  } 
  
  resources :items do
    resources :comments,only: [:create]
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  root 'items#index'

  resources :items do
    member do
      get 'purchase'
      post 'purchase'
      get 'pay'
    end
    collection do
      get 'done'
    end
  end
 
  resources :users do
   resource :logout ,only: [:show]
  end
  resources :credit_cards do
   
  end




  
  
  get 'logouts/show'

end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
  
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  require "payjp"
  before_action :set_card, only: [:destroy,:show]
  def index
    
  end

  def new
    credit_card = CreditCard.where(user_id: current_user.id)
    redirect_to action: "show" if credit_card.exists?
    
  end

  def create #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = Rails.application.credentials.payjp[:payjp_secret_key]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @creditCard = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @creditCard.save
        redirect_to credit_card_path(:id)
      else
        redirect_to action: "create"
      end
    end
  end

 def destroy #PayjpとCardデータベースを削除します
    if @credit_card.blank?
    else
      Payjp.api_key = Rails.application.credentials.payjp[:payjp_secret_key]
      customer = Payjp::Customer.retrieve(@credit_card.customer_id)
      customer.delete
      @credit_card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    if @credit_card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.payjp[:payjp_secret_key]
      customer = Payjp::Customer.retrieve(@credit_card.customer_id)
      @default_card_information = customer.cards.retrieve(@credit_card.card_id)
    end
  end

  def set_card
    @credit_card = CreditCard.where(user_id: current_user.id).first
  end
  
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_compactfooter.html.haml
%footer.sell-footer
  %nav
    %li
      = link_to '#' do
        プライバシーポリシー
    %li
      = link_to '#' do
        メルカリ利用規約
    %li
      = link_to '#' do
        特定商取引に関する表記
  = link_to image_tag("logo.png", size: '140x40'), root_path
  %p
    %small
      &copy; FURIMA, Inc

app/views/credit_cards/_headbottom.haml
%nav.mypagehed-right
  %ul.main-header-user-nav 
    %li
      .main-header-menu-link
        %i.fas.fa-heart
        %span いいね!一覧
    %li
      .main-header-menu-link
        %i.fa.fa-bell
        %span お知らせ
    %li
      .main-header-menu-link
        %i.fa.fa-check
        %span やることリスト
    %li
      .main-header-menu-link
        = link_to "マイページ",users_path, class: "decoration-none" 

app/views/credit_cards/_headmypageleft.haml
.mypagemain-left
  %nav.mypage-nav
    %ul.mypage-nav-list 
      %li.mypage-nav-list-item 
        = link_to users_path, class:"content" do
          マイページ
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item 
        = link_to "#", class:"content" do
          お知らせ
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item  
        = link_to "#", class:"content" do
          やることリスト
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item 
        = link_to "#", class:"content" do
          いいね！一覧
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item  
        = link_to new_item_path, class:"content" do
          出品する
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          下書き一覧
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          出品した商品-出品中
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          出品した商品-取引中
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          出品した商品-売却済み
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item  
        = link_to credit_cards_path, class:"content" do
          購入した商品-取引中
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          購入した商品-過去の取引
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          ニュース一覧
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          評価一覧
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          ガイド
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          お問い合わせ
        %i.fas.fa-angle-right
    %h3.mypage-nav-head メルペイ
    %ul.mypage-nav-list 
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          売上・振込申請
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          ポイント
        %i.fas.fa-angle-right
    %h3.mypage-nav-head 設定
    %ul.mypage-nav-list 
      %li.mypage-nav-list-item 
        = link_to "#", class:"content" do
          プロフィール
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          発送元・お届け先住所変更
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item  
        = link_to credit_cards_path, class:"content" do
          支払い方法
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          メール/パスワード
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          本人情報
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item
        = link_to "#", class:"content" do
          電話番号の確認
        %i.fas.fa-angle-right
      %li.mypage-nav-list-item  
        = link_to logouts_show_path, class:"content" do
          ログアウト
        %i.fas.fa-angle-right

app/views/credit_cards/about.html.haml
.Purchase
  %h1 
    = link_to image_tag("logo.png", size: '140x40'), root_path
.mainpurchase
  %section.mainpurchase-top
    %h2.mainpurchase-top-title 購入内容の確認
    %section.mainpurchase-top-buy
      .mainpurchase-top-buy-item
        .mainpurchase-top-buy-item-box
          %h3.mainpurchase-top-buy-item-box-image
            = image_tag("https://static.mercdn.net/thumb/photos/m48137982118_1.jpg?1587912502", size: "80x80")
          .mainpurchase-top-buy-item-box-detail
            %p.mainpurchase-top-buy-item-box-detail-name 任天堂 スイッチ Joy-Con ネオングリーン/ネオンピンク
            %p.mainpurchase-top-buy-item-box-detail-jp
              %span ¥8,199
              %span.mainpurchase-top-buy-item-box-detail-jp-fee （税込）送料込み
  %section.mainpurchase-price
    .mainpurchase-price-inner
      .mainpurchase-price-inner-item
        %ul.mainpurchase-price-inner-item-list
          %li.mainpurchase-price-inner-item-list-bold
            .mainpurchase-price-inner-item-list-bold-label 支払い金額
            .mainpurchase-price-inner-item-list-bold-cell 
              %span ¥8,199
        %ul.mainpurchase-price-inner-item-point
          %li.mainpurchase-price-inner-item-point-parent
            %i.fas.fa-check
            %label ポイントを使用 (所持ポイント: P0)
  %section.mainpurchase-info
    .mainpurchase-info-pay
      %h3 支払い方法
      %p.mainpurchase-info-pay-text
        %i.fas.fa-check
        %span.mainpurchase-info-pay-text-reg 登録して下さい
  %section.mainpurchase-address
    .mainpurchase-address-inner
      .mainpurchase-address-inner-title
        %h3.mainpurchase-address-inner-title-left 配送先
        = link_to root_path, class:"mainpurchase-address-inner-title-right" do
          %span 変更する
      %address.mainpurchase-address-inner-from
        %br
        %p 〒000-0000
        %br
          東京都米花町0-00
        %br
          江戸川コナン
  %section.mainpurchase-button
    = link_to root_path, method: :delete do
      購入する
  = render "compactfooter"

app/views/credit_cards/create.html.haml
aaaa

app/views/credit_cards/index.html.haml
=render "header"

.topbody__box__below
  .topbody__box__below__search
    .topbody__box__below__search__category             
      = link_to "カテゴリー"             
      = link_to "ブランド"
  =render "headbottom"
%nav.mypagehed2
  %ul.mypagehed2-list
    %li.mypagehed2-list-item 
      = link_to root_path, class:"headmine" do
        フリマ
        %i.fas.fa-angle-right
    %li.mypagehed2-list-item 
      = link_to users_path, class:"headmine" do
        マイページ
        %i.fas.fa-angle-right
    %li.mypagehed2-list-item 
      = link_to new_credit_card_path, class:"headminenow" do
        支払い方法

.mypagemain
  = render "headmypageleft"
  .contentcash
    %section.contentcash-top
      %h2.contentcash-top-head 支払い方法
      .contentcash-top-inner
        %section
          .contentcash-top-inner-content
            %h3.contentcash-top-inner-content-head クレジットカード一覧
          %ul.settings-payment-list
        %section.contentcash-top-inner-add
          .contentcash-top-inner-add-cash
            = link_to credit_card_path(:id), class:"cashbtn-default cashbtn-red cashsubmit_button " do
              %i.fa.fa-credit-card
              クレジットカードを追加する
            
        .contentcash-top-inner-regist  
          = link_to root_path do
            %i.fa.fa-angle-right
            支払い方法について
        

app/views/credit_cards/new.html.haml
=render "header"

.topbody__box__below
  .topbody__box__below__search
    .topbody__box__below__search__category             
      = link_to "カテゴリー"             
      = link_to "ブランド"
  =render "headbottom"
%nav.mypagehed2
  %ul.mypagehed2-list
    %li.mypagehed2-list-item 
      = link_to item_path(:id), class:"headmine" do
        フリマ
        %i.fas.fa-angle-right
    %li.mypagehed2-list-item 
      = link_to users_path, class:"headmine" do
        マイページ
        %i.fas.fa-angle-right
    %li.mypagehed2-list-item 
      = link_to credit_cards_path, class:"headmine" do
        支払い方法
        %i.fas.fa-angle-right
    %li.mypagehed2-list-item
      = link_to new_credit_card_path, class:"headminenow" do
        クレジットカード情報入力

.mypagemain
  = render "headmypageleft"

  .newcredit-right
    %section.newcredit-right-cash
      %h2.newcredit-right-cash-head クレジットカード情報入力
      .newcredit-right-cash-list
        .new-paynumber
          = form_with url: credit_cards_path, method: :post, html: { name: "inputForm", id: "card_token" } do |f|
            = f.label :カード番号, class: "new-paynumber-numbers" 
            %span.new-paynumber-mark 必須
            %input.new-paynumber_zuuzi#card_number{type: "text", placeholder: "半角数字のみ"}
            %ul.newpaycardlist
              = image_tag src="VISA.png" , size: "45x18"
              = image_tag src="master.png" , size: "45x18"
              = image_tag src="jcb.png" , size: "45x18"
            .new-payexpiration
              = f.label :有効期限, class:"new-payexpiration-numbers"
              %span.new-payexpiration-mark 必須
              %br
              .new-payexpiration-list
                .new-payexpiration-list-lists
                  = f.select :exp_month,[["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],class:"new-payexpiration-list-lists_month"
                  %span 月
                .new-payexpiration-list-lists
                  = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],class:"new-payexpiration-list-lists_year"
                  %span 年
            .new-paysecurity
              = f.label :セキュリティコード, class:"new-paysecurity-numbers"
              %span.new-paysecurity-mark 必須
              = f.text_field :seculity_code, placeholder: "カード背面4桁もしくは3桁の番号",class: "new-paysecurity_zuuzi"
              .new-paysecurity-point
                .new-paysecurity-point-text
                  %span カード裏面の番号とは？
                .new-paysecurity-point-info
                #card_token
                = f.submit '追加する', class:"new-paysecurity-point-btn",id:"new-paysecurity-point-btn"

= render "footer"

app/views/credit_cards/show.html.haml
=render "header"

.topbody__box__below
  .topbody__box__below__search
    .topbody__box__below__search__category             
      = link_to "カテゴリー"             
      = link_to "ブランド"
  =render "headbottom"
%nav.mypagehed2
  %ul.mypagehed2-list
    %li.mypagehed2-list-item 
      = link_to root_path, class:"headmine" do
        フリマ
        %i.fas.fa-angle-right
    %li.mypagehed2-list-item 
      = link_to users_path, class:"headmine" do
        マイページ
        %i.fas.fa-angle-right
    %li.mypagehed2-list-item 
      = link_to credit_cards_path, class:"headmine" do
        支払い方法
        %i.fas.fa-angle-right
    %li.mypagehed2-list-item
      = link_to new_credit_card_path, class:"headminenow" do
        クレジットカード情報入力

.mypagemain
  = render "headmypageleft"
  .showcredit-right
    %section.showcredit-right-cash
      %h2.showcredit-right-cash-head 支払い方法
      .showcredit-right-cash-list
        %section
          .showcredit_list
            %h3.showcredit_list_head  クレジットカード一覧 
            %br
            = "**** **** **** " + @default_card_information.last4
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            = form_tag(credit_card_path, method: :delete, id: 'charge-form',  name: "inputForm") do
              %input{ type: "hidden", name: "card_id", value: "" }
              %button 削除する

            
            
   