config/routes.rb
Rails.application.routes.draw do
  
  
  # get 'credit_cards/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions'   
  } 
  
  resources :items do
    resources :comments,only: [:create]
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  root 'items#index'

  resources :items do
    member do
      get 'purchase'
      post 'purchase'
      get 'pay'
    end
    collection do
      get 'done'
    end
  end
 
  resources :users do
   resource :logout ,only: [:show]
  end
  resources :credit_cards do
   
  end




  
  
  get 'logouts/show'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname,        presence: true, uniqueness: true
  validates :email,           presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password,        presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,40}+\z/i }
  validates :first_name,      presence: true, format: { with: /\A[一-龥ぁ-ん]/}
  validates :family_name,       presence: true, format: { with: /\A[一-龥ぁ-ん]/}
  validates :first_name_pseudonym, presence: true, format: { with: /\A[ァ-ヶー－]+\z/}
  validates :family_name_pseudonym,  presence: true, format: { with: /\A[ァ-ヶー－]+\z/}
  validates :birth_year,   presence: true
  validates :birth_month,  presence: true
  validates :birth_day,    presence: true

  validates :address_first_name, null: false, format: { with: /\A[一-龥ぁ-ん]/}
  validates :address_family_name, null: false, format: { with: /\A[一-龥ぁ-ん]/}
  validates :address_first_pseudonym, null: false, format: { with: /\A[ァ-ヶー－]+\z/}
  validates :address_family_pseudonym, null: false, format: { with: /\A[ァ-ヶー－]+\z/}
  validates :post_code, presence: true, format: { with: /\A\d{7}\z/}
  validates :prefecture, presence: true
  validates :city, presence: true
  validates :address_name, presence: true



  has_many :credit_cards
  # -------------
  has_many :items
  has_many :comments
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def sign_up
  #   user = User.new
  # end


  def create
    user = User.create(user_params)
    logger.debug user.errors.inspect
    if user.invalid?
      flash[:alert] = "ブラウザの「戻る」を押し、入力内容を再度ご確認ください。"
      redirect_to new_user_registration_path
    else
      sign_up(user, current_user)
      redirect_to root_path
    end
  end


  private

  def user_params
    params.require(:user).permit(
      :nickname,
      :email,
      :password,
      :password_confirmation,
      :first_name,           
      :family_name,          
      :family_name_pseudonym,  
      :first_name_pseudonym,
      :birth_year,           
      :birth_month,          
      :birth_day,            
      :introduction,
      :avatar,
      :address_first_name,   
      :address_family_name,  
      :address_first_pseudonym, 
      :address_family_pseudonym, 
      :post_code,           
      :prefecture,           
      :city,                 
      :address_name,         
      :building_name,     
      :phone_number    
    )
  end
end


      # session[:nickname] = user_params[:nickname]
      # session[:email] = user_params[:email]
      # session[:password] = user_params[:password]
      # session[:family_name] = user_params[:family_name]
      # session[:first_name] = user_params[:first_name]
      # session[:last_name_pseudonym] = user_params[:last_name_pseudonym]
      # session[:first_name_pseudonym] = user_params[:first_name_pseudonym]
      # session[:birth_year] = user_params[:"birth_year(1i)"].to_i
      # session[:birth_month] = user_params[:"birth_month(2i)"].to_i
      # session[:birth_day] = user_params[:"birth_day(1i)"].to_i

      # session[:address_first_name] = user_params[:address_first_name]
      # session[:address_family_name] = user_params[:address_family_name]
      # session[:address_first_pseudonym] = user_params[:address_first_pseudonym]
      # session[:address_family_pseudonym] = user_params[:address_family_pseudonym]
      # session[:post_code] = user_params[:post_code]
      # session[:prefecture] = user_params[:prefecture]
      # session[:city] = user_params[:city]
      # session[:address_name] = user_params[:address_name]


      # session[:errorname] = user.errors.messages[:nickname].first
      # session[:errormail] = user.errors.messages[:email].first
      # session[:errorpassword] = user.errors.messages[:password].first
      # session[:errorfirstname] = user.errors.messages[:first_name].first
      # session[:errorfamilyname] = user.errors.messages[:family_name].first
      # session[:errorfirstname_pseudonym] = user.errors.messages[:first_name_pseudonym].first
      # session[:errorfamilyname_pseudonym] = user.errors.messages[:family_name_pseudonym].first
      # session[:errorbirth_year] = user.errors.messages[:birth_year].first
      
      # session[:erroraddressfirstname] = user.errors.messages[:address_first_name]
      # session[:erroraddressfamilyname] = user.errors.messages[:address_family_name]
      # session[:erroraddressfirst_pseudonym] = user.errors.messages[:address_first_pseudonym]
      # session[:erroraddressfamily_pseudonym] = user.errors.messages[:address_family_pseudonym]
      # session[:errorpostcode] = user.errors.messages[:post_code]
      # session[:errorprefecture] = user.errors.messages[:prefecture]
      # session[:errorcity] = user.errors.messages[:city]
      # session[:erroraddressname] = user.errors.messages[:address_name]
  
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end

  def new
    
  end
   
  def show
    @user = User.find(params[:id])
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_headbottom.haml
%nav.mypagehed-right
  %ul.main-header-user-nav 
    %li
      .main-header-menu-link
        %i.fas.fa-heart
        %span いいね!一覧
    %li
      .main-header-menu-link
        %i.fa.fa-bell
        %span お知らせ
    %li
      .main-header-menu-link
        %i.fa.fa-check
        %span やることリスト
    %li
      .main-header-menu-link
        = link_to "マイページ",users_path, class: "decoration-none" 

app/views/users/_mypage.html.haml
.topbody__box__below
  .topbody__box__below__search
    .topbody__box__below__search__category             
      = link_to "カテゴリー"             
      = link_to "ブランド"
  %nav.mypagehed-right
    %ul.main-header-user-nav 
      %li
        .main-header-menu-link
          %i.fas.fa-heart
          %span いいね!一覧
      %li
        .main-header-menu-link
          %i.fa.fa-bell
          %span お知らせ
      %li
        .main-header-menu-link
          %i.fa.fa-check
          %span やることリスト
      %li
        .main-header-menu-link
          = link_to "マイページ",root_path, class: "decoration-none" 
%nav.mypagehed2
  %ul.mypagehed2-list
    %li.mypagehed2-list-item 
      = link_to root_path, class:"headmine" do
        メルカリ
        %i.fas.fa-angle-right
    %li.mypagehed2-list-item 
      = link_to root_path, class:"headminenow" do
        マイページ
        %i.fas.fa-angle-right

.mypagemain
  .mypagemain-left
    %nav.mypage-nav
      %ul.mypage-nav-list 
        %li.mypage-nav-list-item 
          マイページ
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          お知らせ
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          やることリスト
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          いいね！一覧
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          出品する
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          下書き一覧
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          出品した商品-出品中
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          出品した商品-取引中
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          出品した商品-売却済み
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          購入した商品-取引中
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          購入した商品-過去の取引
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          ニュース一覧
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          評価一覧
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          ガイド
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          お問い合わせ
          %i.fas.fa-angle-right
      %h3.mypage-nav-head メルペイ
      %ul.mypage-nav-list 
        %li.mypage-nav-list-item  
          売上・振込申請
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          ポイント
          %i.fas.fa-angle-right
      %h3.mypage-nav-head 設定
      %ul.mypage-nav-list 
        %li.mypage-nav-list-item  
          プロフィール
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          発送元・お届け先住所変更
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          = link_to credit_cards_path, class:"content" do
            支払い方法
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          メール/パスワード
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          本人情報
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          電話番号の確認
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          = link_to users_path, class:"content" do
            ログアウト
          %i.fas.fa-angle-right
  .mypagemain-right
    %section.mypage-user
    %section.mypage-user-tab
      %ul.mypage-user-tab-tabs
        %li.newtabs1.active お知らせ
        %li.newtabs1 やることリスト
      %ul.mypage-user-tab-content 
        %li.tabcontent1.show aaaa 
        %li.tabcontent1 bbb
        
          
          
    %section.mypage-tab-container
      %h2.mypage-tab-container-head 購入した商品
      %ul.mypage-tab-item
        %li.newtabs2.active 取引中
        %li.newtabs2 やることリスト
      %ul.mypage-user-tab-content 
        %li.tabcontent2.show aaaa 
        %li.tabcontent2 bbb

app/views/users/destroy.html.haml
//ログアウトページマークアップ仮

=render "header"
.topbody__box__below
  .topbody__box__below__search
    .topbody__box__below__search__category             
      = link_to "カテゴリー"             
      = link_to "ブランド"
  %nav.mypagehed-right
    %ul.main-header-user-nav 
      %li
        .main-header-menu-link
          %i.fas.fa-heart
          %span いいね!一覧
      %li
        .main-header-menu-link
          %i.fa.fa-bell
          %span お知らせ
      %li
        .main-header-menu-link
          %i.fa.fa-check
          %span やることリスト
      %li
        .main-header-menu-link
          = link_to "マイページ",root_path, class: "decoration-none" 
%nav.mypagehed2
  %ul.mypagehed2-list
    %li.mypagehed2-list-item 
      = link_to root_path, class:"headmine" do
        メルカリ
        %i.fas.fa-angle-right
    %li.mypagehed2-list-item 
      = link_to root_path, class:"headminenow" do
        マイページ
        %i.fas.fa-angle-right

.mypagemain
  .mypagemain-left
    %nav.mypage-nav
      %ul.mypage-nav-list 
        %li.mypage-nav-list-item 
          マイページ
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          お知らせ
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          やることリスト
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          いいね！一覧
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          出品する
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          下書き一覧
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          出品した商品-出品中
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          出品した商品-取引中
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          出品した商品-売却済み
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          購入した商品-取引中
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          購入した商品-過去の取引
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          ニュース一覧
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          評価一覧
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          ガイド
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          お問い合わせ
          %i.fas.fa-angle-right
      %h3.mypage-nav-head メルペイ
      %ul.mypage-nav-list 
        %li.mypage-nav-list-item  
          売上・振込申請
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          ポイント
          %i.fas.fa-angle-right
      %h3.mypage-nav-head 設定
      %ul.mypage-nav-list 
        %li.mypage-nav-list-item  
          プロフィール
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          発送元・お届け先住所変更
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          = link_to credit_cards_path, class:"content" do
            支払い方法
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          メール/パスワード
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          本人情報
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          電話番号の確認
          %i.fas.fa-angle-right
        %li.mypage-nav-list-item  
          = link_to new_user_path, class:"content" do
            ログアウト
          %i.fas.fa-angle-right
  .logout-right
    .logout-right-content
      = link_to root_path, method: :delete do
        ログアウト
      

app/views/users/index.html.haml
=render "header"
.topbody__box__below
  .topbody__box__below__search
    .topbody__box__below__search__category             
      = link_to "カテゴリー"             
      = link_to "ブランド"
  = render "headbottom"
%nav.mypagehed2
  %ul.mypagehed2-list
    %li.mypagehed2-list-item 
      = link_to root_path, class:"headmine" do
        フリマ
        %i.fas.fa-angle-right
    %li.mypagehed2-list-item 
      = link_to users_path, class:"headminenow" do
        マイページ
        %i.fas.fa-angle-right

.mypagemain
  =render "headmypageleft"
  .mypagemain-right
    %section.mypage-user
      = image_tag "member_photo.png" , width:70, height:70, class:"kawa-image"
      .mypageimg-top
        =current_user.nickname
      .mypageimg-number
        .mypageimg-number-evalution
          評価
          %span.mypageimg-number-evalution_num
            0
        .mypageimg-number_number
          出品数
          %span.mypageimg-number_number_num
            0
    %section.mypage-user-tab
      %ul.mypage-user-tab-tabs
        %li.newtabs1.active お知らせ
        %li.newtabs1 やることリスト
      %ul.mypage-user-tab-content 
        %li.tabcontent1.show aaaa 
        %li.tabcontent1 bbb
        
          
          
    %section.mypage-tab-container
      %h2.mypage-tab-container-head 購入した商品
      %ul.mypage-tab-item
        %li.newtabs2.active 取引中
        %li.newtabs2 やることリスト
      %ul.mypage-user-tab-content 
        %li.tabcontent2.show aaaa 
        %li.tabcontent2 bbb
=render "footer"