config/routes.rb
Rails.application.routes.draw do
  
  
  # get 'credit_cards/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions'   
  } 
  
  resources :items do
    resources :comments,only: [:create]
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  root 'items#index'

  resources :items do
    member do
      get 'purchase'
      post 'purchase'
      get 'pay'
    end
    collection do
      get 'done'
    end
  end
 
  resources :users do
   resource :logout ,only: [:show]
  end
  resources :credit_cards do
   
  end




  
  
  get 'logouts/show'

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :category
  # belongs_to :brand #optional: true
  belongs_to :user
  has_many :images
  has_many :comments
  # belongs_to :brand
  # belongs_to :user #optional: true#through:comments

  #画像複数投稿
  accepts_nested_attributes_for :images, allow_destroy: true
  #必須（画像）
  validates :images,presence: true #length: { minimum: 1, message: "が入力されていません" }
  #必須（商品名40文字以内）
  validates :name, presence: true, length: { maximum: 40}
  validates :images,presence: true #length: { minimum: 1, message: "が入力されていません" }
  validates :introduction, presence: true, length: { maximum: 1000 }
  #必須（価格300~9,999,999）
  validates :price, presence: true , numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  #必須（カテゴリー、商品の状態、発送元地域、発送までの日数、配送料の負担者、）
  validates  :category_id, :item_condition, :shipping_area, :preparation_day, :trading_status, presence: true
  validates :category_id, presence: true

  enum item_condition: {
    新品、未使用:1, 未使用に近い:2, 目立った傷や汚れなし:3, やや傷や汚れあり:4, 傷や汚れあり:5, 全体的に状態が悪い:6
  }
  enum shipping_area: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,岐阜県:21,静岡県:22,愛知県:23,三重県:24,滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,徳島県:36,香川県:37,愛媛県:38,高知県:39,福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  enum trading_status: {
    送料込み:1, 着払い:2
  }
  enum postage_type: {
    未定:1, クロネコヤマト:2, ゆうパック:3, ゆうメール:4, らくらくフリマ便:5, レターパック:6, 普通郵便（定形、定形外）:7, クリックポスト:8, ゆうパケット:9
  }
  enum preparation_day: {
    １〜２日で発送:1, ２〜３日で発送:2, ４〜７日で発送:3
  }
  enum brand_id:{
    ナイキ:1
  }


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :show, :destroy, :update, :purchase, :pay]
  before_action :set_card, only: [:purchase, :pay]
  before_action :category_parents, only: [:new, :edit]
  def index
    @items = Item.includes(:images).order('created_at DESC').limit(9)
    @parents = Category.where(ancestry: nil)
  end

# カテゴリーセレクトボックスの設定
  def category_parents
    #セレクトボックスの初期値設定
    @category_parent_array = []
    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).limit(13).each do |parent|
      @category_parent_array << parent
    end
  end

  def new
    @item = Item.new
    @item.images.new
  end


  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:alert] = "商品が出品されました。"
      redirect_to root_path
    else
      @item.images.new
      @category_parent_array = []
      Category.where(ancestry: nil).limit(2632).each do |parent|
        @category_parent_array << parent
      end
      flash[:alert] = "必須項目をご確認ください。"
      render :new
    end
  end
  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    respond_to do |format|
      format.html
      format.json do
      @category_children = Category.where(ancestry: "#{params[:parent_id]}")
      #親カテゴリーに紐付く子カテゴリーを取得
      end
    end
  end 
    # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #binding.pry
    # @category_grandchildren = Category.where(ancestry: "#{params[:child_id]}")
    category=Category.find(params[:child_id])
    @category_grandchildren=category.children
    #子カテゴリーに紐付く孫カテゴリーの配列を取得
  end

  def show
    @parents = Category.all.order("id ASC").limit(1316)
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def edit
  end

  def update
    # binding.pry
    if @item.update(item_update_params)
      flash[:alert] = "出品商品が編集されました。"
      redirect_to root_path
    else
      @item.images=Image.where(item_id:@item.id)
      @category_parent_array = []
    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).limit(13).each do |parent|
      @category_parent_array << parent
    end
      flash[:alert] = "必須項目をご確認ください。"
      render action: :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else 
      render show
    end
  end
  
  def purchase
    if @credit_card.blank?
      redirect_to controller: 'credit_cards', action: 'new'
    else
      Payjp.api_key = Rails.application.credentials.payjp[:payjp_secret_key]
      customer = Payjp::Customer.retrieve(@credit_card.customer_id)
      @default_card_information = customer.cards.retrieve(@credit_card.card_id)
    end
    
    
  end

  def pay
    Payjp.api_key = Rails.application.credentials.payjp[:payjp_secret_key]
    Payjp::Charge.create(
    amount: @item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
    customer: @credit_card.customer_id, #顧客ID
    currency: 'jpy', #日本円
    )
  @product_purchaser= Item.find(params[:id])
    if @product_purchaser.update( buyer_id: current_user.id)
      redirect_to controller: 'items', action: 'index' #完了画面に移動
    else 
      redirect_to controller: 'items', action: 'purchase'
    end
  end

  def done
  end
  def set_item
    @item = Item.find(params[:id])
  end
  
  def set_card
    @credit_card = CreditCard.where(user_id: current_user.id).first
  end
  
  private

  def item_params
    params.require(:item).permit(:name, :price, :introduction, :category_id, :item_condition, :brand_id, :shipping_area, :preparation_day, :trading_status, :postage_type, images_attributes: [:url]).merge(user_id: current_user.id)
  end

  
  def item_update_params
    params.require(:item).permit(:name, :price, :introduction, :category_id, :item_condition, :brand_id, :shipping_area, :preparation_day, :trading_status, :postage_type, images_attributes: [:url, :id, :_destroy]).merge(user_id: current_user.id)
      
  end

  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_compactfooter.html.haml
%footer.sell-footer
  %nav
    %li
      = link_to '#' do
        プライバシーポリシー
    %li
      = link_to '#' do
        FURIMA利用規約
    %li
      = link_to '#' do
        特定商取引に関する表記
  = link_to image_tag("logo.png", size: '140x40'), root_path
  %p
    %small
      &copy; FURIMA, Inc

app/views/items/_showitem.html.haml
.highspace 
  - if user_signed_in? 
    .highspace__opening
      %a 出品する
      =link_to new_item_path do
        %i.fas.fa-camera
  .highspace__area__choice
    .highspace__area__choice__find
      .highspace__area__choice__find__type             
        = link_to "カテゴリー"             
        = link_to "ブランド"
    .highspace__area__choice__people
      .highspace__area__choice__people__lineup
        - if user_signed_in?
          .highspace__area__choice__people__lineup__gate
            = link_to "フリマ", root_path, class: "member_right"
          = link_to "マイページ", users_path, class: "newreg"
        - else
          .highspace__area__choice__people__lineup__gate
            = link_to "ログイン", root_path, class: "member_right"
          = link_to "新規会員登録", root_path, class: "newreg"
  
  %nav.breadCrumbs
    %ul.breadCrumbs__list
      %li.breadCrumbs__list__item 
        = link_to root_path, class:"content" do
          FURIMA
          %i.fas.fa-angle-right
      %li.breadCrumbs__list__item 
        = link_to root_path, class:"content" do
          - @parents.each do |parent|
            - if @item.category_id == parent.id #取り出したIDと商品のIDが同じ物を表示
              = parent.parent.parent.name #親カテゴリー
          %i.fas.fa-angle-right
      %li.breadCrumbs__list__item 
        = link_to root_path, class:"content" do 
          - @parents.each do |parent|
            - if @item.category_id == parent.id #取り出したIDと商品のIDが同じ物を表示
              = parent.parent.name #親カテゴリー
          %i.fas.fa-angle-right
      %li.breadCrumbs__list__item 
        = link_to root_path, class:"content" do
          - @parents.each do |parent|
            - if @item.category_id == parent.id #取り出したIDと商品のIDが同じ物を表示
              = parent.name #親カテゴリー
          %i.fas.fa-angle-right
      %li.breadCrumbs__list__item 
        %p=@item.name
  
  .main
    .main__whole
      .main__whole__center
        .main__whole__center__box
          .main__whole__center__box__content
            %h2.main__whole__center__box__content__name
              %p=@item.name
            .main__whole__center__box__content__list
              %ul
                %li
                  = image_tag (@item.images.first.url.url.to_s)
                    -if @item.buyer_id.present? 
                    .main__whole__center__box__content__list_sold
                      .main__whole__center__box__content__list_sold-inner
                        SOLD
                %ul
                  - @item.images.each do |images|
                    = image_tag (images.url.url.to_s)

            .main__whole__center__box__content__price
              %span 
                ¥
                = @item.price
              .main__whole__center__box__content__price-detail
                %p1
                  = "(税込)"
                %p1
                  = "送料込み"
                -if @item.buyer_id.present? 
                  .main__whole__center__box__content__price-purchase
                    .main__whole__center__box__content__price-purchase-sold
                      売り切れました
                - if user_signed_in?&& current_user.id != @item.user_id
                  -if user_signed_in?&& current_user.id=@item.buyer_id
                  - else
                    .main__whole__center__box__content__price-purchase
                    = link_to purchase_item_path(@item.id), class: "main_purchase_btn" do
                      購入画面にすすむ
              
            .main__whole__center__box__content__description
              =@item.introduction
            .main__whole__center__box__content__table
              %table
                %tbody
                  %tr
                    %th 出品者
                    %td
                      =@item.user.nickname
                  %tr
                    %th カテゴリー
                    %td
                      - @parents.each do |parent| #eachで全てを取り出す。
                        - if @item.category_id == parent.id #取り出したIDと商品のIDが同じ物を表示
                          = parent.parent.parent.name #親カテゴリー
                          %br
                          = parent.parent.name #子カテゴリー
                          %br
                          = parent.name #孫カテゴリー
                    %tr
                      %th ブランド
                      %td=@item.brand_id
                    %tr
                    - if @items.present?
                      %th 商品のサイズ
                      %td
                    %tr
                      %th 商品の状態
                      %td=@item.item_condition
                    %tr
                      %th 配送料の負担
                      %td=@item.trading_status
                    %tr
                    %th 発送元の地域
                    %td
                      = link_to root_path, class:"" do
                        =@item.shipping_area
                    %tr
                      %th 発送日の目安
                      %td=@item.preparation_day
              .main__whole__center__box__content__optionalzone
                %ul
                  %li.main__whole__center__box__content__optionalzone__like-Btn
                    %i.fa.fa-star
                    %textお気に入り 0
                %ul
                  %li.main__whole__center__box__content__optionalzone__out-Btn
                    = link_to root_path, class:"" do
                      %i.fa.fa-flag
                      %text不適切な商品の通報

            - if user_signed_in?&& current_user.id == @item.user_id
              -if @item.buyer_id.blank? 
                .shousaiedit
                  =link_to edit_item_path , class:"showsaibtn" do
                    編集する
                    
                  %p.shousaidestroy
                    =link_to item_path , class:"showsaibtn"  ,method: :delete do
                      削除する

          
          .main__whole__center__comment-room
            - if @comments.present?
              %ul.main__whole__center__comment-room__Contents
                .comments
                  - if @comments
                    - @comments.each do |comment|
                      = image_tag "member_photo.png" , width:35, height:35, class:"kawa-image"
                      .comments-name
                        = comment.user.nickname
                      .comments-box
                        .comments-box__text
                          = comment.comment
                        .comments-box__date
                          %time(datetime="#{comment.created_at}")= time_ago_in_words(comment.created_at) + "前"
            %p.main__whole__center__comment-room__Contents__new-comment__noticeMsg
              相手のことを考え丁寧なコメントを心がけましょう。
              %br/
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
              %br/
            .main__whole__center__comment-room__Contents__new-comment
              = form_with model: [@item, @comment], local: true do |f|
                = f.text_area :comment,{class: 'main__whole__center__comment-room__Contents__new-comment__comment-body', required: "required"}
                = f.hidden_field :item_id, value: @item.id
                = f.submit "コメントする",class: "main__whole__center__comment-room__Contents__new-comment__btn"


          %ul.main__whole__center__links
            %li.main__whole__center__links__f
              = link_to root_path, class:"" do
                %i.fa.fa-angle-left
                %span 前の商品
            %li.main__whole__center__links__r
              = link_to root_path, class:"" do
                %span 後ろの商品
                %i.fas.fa-angle-right

          .main__whole__center__relatedItems
            = link_to root_path, class:"" do
              - @parents.each do |parent| #eachで全てを取り出す。
                - if @item.category_id == parent.id #取り出したIDと商品のIDが同じ物を表示
                  = parent.parent.parent.name #親カテゴリー
                  をもっと見る
            .main__whole__center__relatedItems__productLists
            %after.main__whole__center__relatedItems__relatedItems

app/views/items/_topbody.html.haml
.topbody  
  - if user_signed_in? 
    .topbody__exhibition
      %a出品する
      =link_to new_item_path do
        %i.fas.fa-camera
  .topbody__box__below
    .topbody__box__below__search
      .topbody__box__below__search__category          
        = render "categories"
    %nav.mypagehed-right
    - if user_signed_in?
      %ul.main-header-user-nav
        %li
          .main-header-menu-link
            %i.fas.fa-heart
            %span いいね!一覧
        %li
          .main-header-menu-link
            %i.fa.fa-bell
            %span お知らせ
        %li
          .main-header-menu-link
            %i.fa.fa-check
            %span やることリスト
        %li
          .main-header-menu-link
            = link_to "マイページ",users_path, class: "decoration-none"
        -# %li
        -#   .main-header-menu-link      
        -#     %i.far.fa-star
        -#     = link_to "ログアウト(仮)", destroy_user_session_path, method: :delete, class: 'btn'
    
    - else
      .topbody__box__below__users__member  
        .topbody__box__below__users__member__right
          = link_to "ログイン", new_user_session_path, class: "member_right"
        = link_to "新規会員登録", new_user_registration_path, class: "newreg"

  .topbody__image
    .topbody__image__photos
      .topbody__image__photos__text
        %b1 人生を変える
        %b2 フリマアプリ
        %b3 FURIMAはだれでもかんたんに出品・購入できる
        %b4 フリマアプリです
      .topbody__image__photos__stores
        = link_to 'https://apps.apple.com/jp/app/id667861049?l=ja', class: "appstore" do
          = image_tag 'appstore.svg', size: '170x52'
        = link_to 'https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja', class: "googleplay" do
          = image_tag 'googleplay.svg', size: '520x52'
  .topbody__reasons
    .topbody__reasons__subtitle
      FURIMAが選ばれる3つの理由
    %ul.topbody__reasons__lists
      %li.topbody__reasons__lists__list
        .topbody__reasons__lists__list__photo
          .topbody__reasons__lists__list__photo__number
            1
          = image_tag "pict-reason-01.jpg", height: '300px', width: '300px'
        .topbody__reasons__lists__list__text
          %span
            ３分
          #text
            ですぐに出品
        %p.topbody__reasons__lists__list__comment
          スマホで入力するだけで簡単に出品できる！
      %li.topbody__reasons__lists__list
        .topbody__reasons__lists__list__photo
          .topbody__reasons__lists__list__photo__number
            2
          = image_tag "pict-reason-02.jpg", height: '300px', width: '300px'
        .topbody__reasons__lists__list__text
          %span 
            シンプル
          #text
            で使いやすい
        %p.topbody__reasons__lists__list__comment
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.topbody__reasons__lists__list
        .topbody__reasons__lists__list__photo
          .topbody__reasons__lists__list__photo__number
            3
          = image_tag "pict-reason-03.jpg", height: '300px', width: '300px'
        .topbody__reasons__lists__list__text
          %span 
            手数料
          #text
            業界最安値
        %p.topbody__reasons__lists__list__comment
          最大３%でお得に出品&購入！

  .topbody__ads
    .topbody__ads__bl
      .topbody__ads__bl__title
        会員数日本一
      .topbody__ads__bl__text
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です! 
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .topbody__ads__bl__btn
        = link_to 'https://apps.apple.com/jp/app/id667861049?l=ja', class: "appstore" do
          = image_tag 'appstore.svg', size: '170x52'
        = link_to 'https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja', class: "googleplay" do
          = image_tag 'googleplay.svg', size: '170x52'
        

  .topbody__point
    .topbody__point__title
      FURIMAの特徴
    .topbody__point__indexes
      .topbody__point__indexes__index
        = image_tag("icon-01.png", size: "184x270")
        .topbody__point__indexes__index__sub
          簡単に売り買いできる
        .topbody__point__indexes__index__comment
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .topbody__point__indexes__index
        = image_tag("icon-03.png", size: "184x270")
        .topbody__point__indexes__index__sub
          売上金は即日振込みに対応
        .topbody__point__indexes__index__comment
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
      .topbody__point__indexes__index
        = image_tag("icon-04.png", size: "184x270")
        .topbody__point__indexes__index__sub
          様々な支払いに対応
        .topbody__point__indexes__index__comment
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  .topbody__pickup
    .topbody__pickup__title
      ピックアップカテゴリー
    .topbody__pickup__indexes
      .topbody__pickup__indexes__sub
        新規投稿商品
      .topbody__pickup__indexes__categories
        - @items.each do |item|
          .topbody__pickup__indexes__categories__category
            -if item.buyer_id.present? 
              .topbody__pickup__indexes__categories__category_sold
                .topbody__pickup__indexes__categories__category_sold-inner
                  SOLD
            = link_to asset_url("/items/#{item.id}", method: :get) do
              = image_tag (item.images.first.url.url.to_s)
            .topbody__pickup__indexes__categories__category__lists
              .topbody__pickup__indexes__categories__category__lists__name
                %span.name
                  = item.name
                    
              .topbody__pickup__indexes__categories__category__lists__datas
                %ul.topbody__pickup__indexes__categories__category__lists__datas__data
                  %li.topbody__pickup__indexes__categories__category__lists__datas__data__price
                    %span.price
                      = item.price
                      円
                  %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes
                    %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes__like
                      %i.fas.fa-star 
                        0
                %p.topbody__pickup__indexes__categories__category__lists__datas__data__tax
                  (税込)
      
  .topbody__pickup
    .topbody__pickup__title
      ピックアップブランド
    .topbody__pickup__indexes
      .topbody__pickup__indexes__sub
        アーカイバ
      .topbody__pickup__indexes__categories
        .topbody__pickup__indexes__categories__category
          = image_tag("egg.png", size: "184x184")
          .topbody__pickup__indexes__categories__category__lists
            .topbody__pickup__indexes__categories__category__lists__name
              魅惑的な白身魚
            .topbody__pickup__indexes__categories__category__lists__datas
              %ul.topbody__pickup__indexes__categories__category__lists__datas__data
                %li.topbody__pickup__indexes__categories__category__lists__datas__data__price
                  20,000円
                %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes
                  %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes__like
                    %i.fas.fa-star 
                      0
              %p.topbody__pickup__indexes__categories__category__lists__datas__data__tax
                税込
        .topbody__pickup__indexes__categories__category
          = image_tag("egg.png", size: "184x184")
          .topbody__pickup__indexes__categories__category__lists
            .topbody__pickup__indexes__categories__category__lists__name
              魅惑的な白身魚
            .topbody__pickup__indexes__categories__category__lists__datas
              %ul.topbody__pickup__indexes__categories__category__lists__datas__data
                %li.topbody__pickup__indexes__categories__category__lists__datas__data__price
                  20,000円
                %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes
                  %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes__like
                    %i.fas.fa-star 
                      0
              %p.topbody__pickup__indexes__categories__category__lists__datas__data__tax
                税込
        .topbody__pickup__indexes__categories__category
          = image_tag("egg.png", size: "184x184")
          .topbody__pickup__indexes__categories__category__lists
            .topbody__pickup__indexes__categories__category__lists__name
              魅惑的な白身魚
            .topbody__pickup__indexes__categories__category__lists__datas
              %ul.topbody__pickup__indexes__categories__category__lists__datas__data
                %li.topbody__pickup__indexes__categories__category__lists__datas__data__price
                  20,000円
                %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes
                  %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes__like
                    %i.fas.fa-star 
                      0
              %p.topbody__pickup__indexes__categories__category__lists__datas__data__tax
                税込
      .topbody__pickup__indexes__categories
        .topbody__pickup__indexes__categories__category
          = image_tag("egg.png", size: "184x184")
          .topbody__pickup__indexes__categories__category__lists
            .topbody__pickup__indexes__categories__category__lists__name
              魅惑的な白身魚
            .topbody__pickup__indexes__categories__category__lists__datas
              %ul.topbody__pickup__indexes__categories__category__lists__datas__data
                %li.topbody__pickup__indexes__categories__category__lists__datas__data__price
                  20,000円
                %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes
                  %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes__like
                    %i.fas.fa-star 
                      0
              %p.topbody__pickup__indexes__categories__category__lists__datas__data__tax
                税込          
        .topbody__pickup__indexes__categories__category
          = image_tag("egg.png", size: "184x184")
          .topbody__pickup__indexes__categories__category__lists
            .topbody__pickup__indexes__categories__category__lists__name
              魅惑的な白身魚
            .topbody__pickup__indexes__categories__category__lists__datas
              %ul.topbody__pickup__indexes__categories__category__lists__datas__data
                %li.topbody__pickup__indexes__categories__category__lists__datas__data__price
                  20,000円
                %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes
                  %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes__like
                    %i.fas.fa-star 
                      0
              %p.topbody__pickup__indexes__categories__category__lists__datas__data__tax
                税込
        .topbody__pickup__indexes__categories__category
          = image_tag("egg.png", size: "184x184")
          .topbody__pickup__indexes__categories__category__lists
            .topbody__pickup__indexes__categories__category__lists__name
              魅惑的な白身魚
            .topbody__pickup__indexes__categories__category__lists__datas
              %ul.topbody__pickup__indexes__categories__category__lists__datas__data
                %li.topbody__pickup__indexes__categories__category__lists__datas__data__price
                  20,000円
                %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes
                  %li.topbody__pickup__indexes__categories__category__lists__datas__data__likes__like
                    %i.fas.fa-star 
                      0
              %p.topbody__pickup__indexes__categories__category__lists__datas__data__tax
                税込

app/views/items/a.html.haml
= f.text_field :カラム名, required: true

app/views/items/destroy.html.haml
削除しました

app/views/items/index.html.haml
.wrapper
  = render "header"
  = render "topbody"
  = render "footer"

app/views/items/purchase.html.haml
.sell
  %header.sell-header
    = link_to image_tag("logo.png", size: '140x40'), root_path
.mainpurchase
  %section.mainpurchase-top
    %h2.mainpurchase-top-title 購入内容の確認
    %section.mainpurchase-top-buy
      .mainpurchase-top-buy-item
        .mainpurchase-top-buy-item-box
          %h3.mainpurchase-top-buy-item-box-image
            = image_tag(@item.images.first.url.url.to_s ,size: "80x80")
          .mainpurchase-top-buy-item-box-detail
            %p.mainpurchase-top-buy-item-box-detail-name 
              =@item.name
            %p.mainpurchase-top-buy-item-box-detail-jp
              %span
                ¥
                =@item.price
              %span.mainpurchase-top-buy-item-box-detail-jp-fee 
                （税込）
                =@item.trading_status
  %section.mainpurchase-price
    .mainpurchase-price-inner
      .mainpurchase-price-inner-item
        %ul.mainpurchase-price-inner-item-list
          %li.mainpurchase-price-inner-item-list-bold
            .mainpurchase-price-inner-item-list-bold-label 支払い金額
            .mainpurchase-price-inner-item-list-bold-cell 
              %span 
                ¥
                =@item.price
        %ul.mainpurchase-price-inner-item-point
          %li.mainpurchase-price-inner-item-point-parent
            %input.point__checkbox{type:"checkbox", value:"0"}
            %label ポイントを使用 (所持ポイント: P0)
  %section.mainpurchase-info
    .mainpurchase-info-pay
      .mainpurchase-info-pay-form
        .mainpurchase-info-pay-form 支払い方法
        = link_to credit_card_path(:id), class:"mainpurchase-info-pay-form-right" do
          %span 変更する
      %p.mainpurchase-info-pay-text
        %br
        = "**** **** **** " + @default_card_information.last4
        %br
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
  %section.mainpurchase-address
    .mainpurchase-address-inner
      .mainpurchase-address-inner-title
        %h3.mainpurchase-address-inner-title-left 配送先
      %address.mainpurchase-address-inner-from
        %br
        %p 
          〒
          =@item.user.post_code
        %br
          =@item.user.prefecture+@item.user.city+@item.user.address_name+@item.user.building_name
        %br
          =@item.user.address_first_name+@item.user.address_family_name
  %section.mainpurchase-button
    = link_to pay_item_path(@item), method: :get do
      購入する
  = render "compactfooter"